---

owncloud__domain: [ 'localhost.localdomain' ]

## Ensure that LibreOffice is not installed for testing the role.
owncloud__app_documents_enabled: False


## https://travis-ci.org/ypid/ansible-owncloud/builds/150109046
##
## Failed to validate the X.509 certificate for download.owncloud.org:443. Make
## sure your managed systems have a valid CA certificate installed. If the
## website serving the url uses SNI you need python >= 2.7.9 on your managed
## machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and
## `pyasn1` python modules to perform SNI verification in python >= 2.6. You can
## use validate_certs=False if you do not need to confirm the servers identity
## but this is unsafe and not recommended. Paths checked for this platform:
## /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs,
## /usr/share/ca-certificates/cacert.org, /etc/ansible
##
## sudo apt-get install -y python-pyasn1 python-urllib3
## In before executing the role in CI test did not solve it.
owncloud__apt_repo_key_url: 'http://{{ owncloud__apt_repo_base + "/" +
                             owncloud__distribution + "/"
                             "Release.key" }}'
